# Generated by Django 6.0 on 2026-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='date',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_uploads/'),
        ),
    ]
