# Generated by Django 6.0 on 2026-03-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_audio_audio_remove_audio_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='audio',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='audio',
            name='filesize',
            field=models.BigIntegerField(default=0),
        ),
    ]
