# Generated by Django 6.0 on 2026-03-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_audio_audio_audio_date_audio_filename_audio_filesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='date',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='filesize',
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
