# Generated by Django 6.0 on 2026-03-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_audio_audio_audio_date_audio_filename_audio_filesize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='locked_docs/')),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('filesize', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('REGISTRATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='LockedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('REGISTRATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
            options={
                'unique_together': {('app_key', 'REGISTRATION')},
            },
        ),
    ]
