# Generated by Django 6.0 on 2026-03-11 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_lockeddocument_lockedapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='user_complaint_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
